### ISSUE TITLE
select a block by its index ?

### ISSUE THREAD

**Issue by mh-cbon** [suntong/cascadia#1]
hi!

any idea how to do that ?

```sh
curl --silent https://en.wikipedia.org/wiki/Changelog | cascadia -i -o -c '#mw-content-text > p[0]'
```

**Comment by suntong** [comment]
Ops, I'll look into that. 

So, you want to get this from above command? 

`<p>A <b>changelog</b> is a log or record of all notable changes made to a project. The project is often a <a href="/wiki/Website" title="Website">website</a> or software project, and the changelog usually includes records of changes such as bug fixes, new features, etc. Some <a href="/wiki/Open_source" class="mw-redirect" title="Open source">open source</a> projects include a changelog as one of the top level files in their distribution.</p>
`

**Comment by suntong** [comment]
If so, the syntax should be, 

- `#mw-content-text > p:first-child`, or
- `div#mw-content-text > p:nth-child(0)`

However, that's not working with my `cascadia`. I'll look into that as well.

**Comment by suntong** [comment]
Oh, chrome tells me it is `nth-child(2)` instead of `nth-child(0)`. So, 

```
$ curl --silent https://en.wikipedia.org/wiki/Changelog | cascadia -i -o -c 'div#mw-content-text > p:nth-child(2)'
1 elements for 'div#mw-content-text > p:nth-child(2)':
<p>A <b>changelog</b> is a log or record of all notable changes made to a project. The project is often a <a href="/wiki/Website" title="Website">website</a> or software project, and the changelog usually includes records of changes such as bug fixes, new features, etc. Some <a href="/wiki/Open_source" class="mw-redirect" title="Open source">open source</a> projects include a changelog as one of the top level files in their distribution.</p>
```

I'll check the return of `cascadia.MustCompile` next to fix the crash.

**Comment by suntong** [comment]
FYI, Best CSS Selector Reference I found:
http://www.w3schools.com/cssref/css_selectors.asp

**Comment by mh-cbon** [comment]
oh ok awesome!

I d say the README just need more examples of css selectors to make it clear we are dealing with it.
I admit i quickly read the readme >.<

thanks!

**Comment by suntong** [comment]
k. will do.
