### ISSUE TITLE
Undefined "github.com/go-easygen/cli".DenseNormalStyle

### ISSUE THREAD

**Issue by digglife** [suntong/cascadia#5]
Seems that `DenseNormalStyle` is from `github.com/mkideal/cli`, but the one imported in `cascadia_main.go` is  `github.com/go-easygen/cli`.

```bash
go get github.com/suntong/cascadia                                                                                              130 ↵
go: finding github.com/suntong/cascadia latest
# github.com/suntong/cascadia
../../go/pkg/mod/github.com/suntong/cascadia@v0.0.0-20180522160600-2b4a1051d626/cascadia_main.go:55:20: undefined: "github.com/go-easygen/cli".DenseNormalStyle
```

**Comment by suntong** [comment]
Thanks for reporting, I'll take a look...

**Comment by suntong** [comment]
There was a long~~~ story why it got to a situation like this, but... fixed now anyway. 
Let me know if it doesn't work for you.

**Comment by digglife** [comment]
@suntong 

It works. Thank you!
